### ISSUE TITLE
pip install pyklib

### ISSUE THREAD

**Issue by kapoorlab** [bhoeckendorf/pyklb#10]
Hello, I am building a napari plugin that can take in different formats of the light sheet images and one of the dependency of the plugin called vollseg in the klb file format. Since it is not a pip package it is difficult to have this dependency automatically satisfied during the installation of the plugin I am building. Do you think it would be possible to make this as a standard pip package and release it on pypi?

**Comment by bhoeckendorf** [comment]
Would it work for you to use use `git+https://github.com/bhoeckendorf/pyklb.git@skbuild` as dependency instead of `pyklb`? I understand that this isn't ideal, but if it works for you it would be the easiest for everyone.

KLB isn't a widely used file format and unless this changes unexpectedly, this package is effectively in maintenance mode.  You may want to focus your attention to more widely adopted and better supported formats like [zarr](https://github.com/zarr-developers/zarr-python), which has also been adopted by the OME team ([ome-zarr](https://github.com/ome/ome-zarr-py)).

I'm curious. Are you encountering any .klb files in the wild? If so, and if switching to another format is not an option for some reason, we can revisit this issue and look for a better solution.

**Comment by kapoorlab** [comment]
Hi @bhoeckendorf , This is what I have been doing so far and that works yes, I just wanted it to be a pip package so the end users are not confused about this dependency, I added this way of installing the package by adding it in the setup.py file of my package but pip does not automatically picks it up: [dependency in setup](https://github.com/kapoorlab/VollSeg/blob/main/setup.py). 

Ah and I did not realize that this was in maintenance mode, I just saw the data coming from Patrick Lemaire and it was inr.gz format, so I included a reader for that and the other formats for the light sheet data that I found were klb, tif and h5 so thought of adding their readers in Napari. But if it is not so widely used I can indeed skip it for the zarr format instead. So I think for now we can close this issue and revisit it later if necessary. Many thanks.
